# Project information
site_name: Multimap
site_url: http://multimap.io
repo_url: https://bitbucket.org/mtrenkmann/multimap
site_description: 1:n key-value store for C++ and Java
site_author: Martin Trenkmann
copyright: Copyright © 2015 <a href="mailto:martin@multimap.io">Martin Trenkmann</a>
google_analytics: null
remote_branch: null
remote_name: null

# Documentation layout
pages:
  - Home: index.md
  - Overview: overview.md
  - Tutorial:
    - 'For C++ Developers': 'tutorial-cpp.md'
    - 'For Java Developers': 'tutorial-java.md'
  - Reference:
    - 'C++ API': 'reference-cpp.md'
    - 'Java API': 'reference-java.md'
  - Download: download.md
#  - Donate: donate.md

# Build directories
theme: yeti
theme_dir: doc/theme
docs_dir: doc
extra_css: ['https://fonts.googleapis.com/css?family=Faster+One|Inconsolata', multimap.css]

# Others
include_next_prev: false
extra:
  twitter_url: https://twitter.com/multimapio


