site_name: Multimap
theme_dir: docs/theme
pages:
  - Home: 'index.md'
  - Overview: 'overview.md'
  - Tutorials:
    - 'For C++ Developers': 'cpptutorial.md'
    - 'For Java Developers': 'javatutorial.md'
  - Reference:
    - 'For C++ Developers': 'cppreference.md'
    - 'For Java Developers': 'javareference.md'
  - Downloads:
    - 'Release 0.3': 'downloadv03.md'
    - 'Release 0.2': 'downloadv02.md'
    - 'Release 0.1': 'downloadv01.md'
    - 'Changelog': 'changelog.md'