# Project information
site_name: Multimap - a 1:n key-value store
repo_url: https://bitbucket.org/mtrenkmann/multimap
site_description: 1:n key-value store for C++ and Java
site_author: Martin Trenkmann
copyright: Copyright © 2015 <a href="mailto:martin@multimap.io">Martin Trenkmann</a>
google_analytics: null
remote_branch: null
remote_name: null

# Documentation layout
pages:
  - Home: index.md
  - Overview: overview.md
  - Tutorial:
    - 'for C++ Developers': 'cpptutorial.md'
    - 'for Java Developers': 'javatutorial.md'
  - Reference:
    - 'for C++ Developers': 'cppreference.md'
    - 'for Java Developers': 'javareference.md'
  - Download: download.md

# Build directories
theme: yeti
theme_dir: doc/theme
docs_dir: doc
extra_css: ['https://fonts.googleapis.com/css?family=Faster+One|Inconsolata', multimap.css]

# Others
include_next_prev: false
extra:
  twitter_url: https://twitter.com/multimapio

