site_name: Multimap
theme_dir: docs/theme
pages:
  - Home: index.md
  - Overview: overview.md
  - Tutorials:
    - C++:
      - 'Basics': cppbasics.md
    - Java:
      - 'Basics': javabasics.md
  - Reference:
    - 'C++ Reference': cppreference.md
    - 'Java Reference': javareference.md
  - Downloads:
    - 'Release 0.3': downloadv03.md
    - 'Changelog': changelog.md
