# Project information
site_name: Multimap
site_url: http://multimap.io
repo_url: https://bitbucket.org/mtrenkmann/multimap
site_description: The 1:n key-value store.
site_author: Martin Trenkmann
site_favicon: theme/favicon.ico
copyright: Copyright © 2015 <a href="mailto:martin@multimap.io">Martin Trenkmann</a>
google_analytics: null
remote_branch: null
remote_name: null

# Documentation layout
pages:
  - Home: index.md
  - C++: cpp.md
  - Java: java.md
  - Download: download.md

# Build directories
theme: yeti  # Take mkdocs' blue color
theme_dir: docs/theme
site_dir: site  # docs/site does not work properly
extra_css: ['http://fonts.googleapis.com/css?family=Faster+One', 'http://fonts.googleapis.com/css?family=Inconsolata', multimap.css]

# Others
include_next_prev: false
extra:
  twitter_url: https://twitter.com/multimapio


